version: "3.8"

services:

  accounts:
    image: frannnnk/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - frank-network
    
  loans:
    image: frannnnk/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - frank-network
    
  cards:
    image: frannnnk/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - frank-network
    
networks:
  frank-network: