version: "3.7"

services:

  configserver:
    image: frannnnk/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - frannnnk

  accounts:
    image: frannnnk/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - frannnnk
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 15
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: frannnnk/loans:latest
    ports:
      - "8090:8090"
    networks:
      - frannnnk
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: frannnnk/cards:latest
    ports:
      - "9000:9000"
    networks:
      - frannnnk
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  frannnnk: